### ISSUE TITLE
Really compatible with lua-5.1?

### ISSUE THREAD

**Issue by ff2000** [simoncozens/sile#103]
I built sile with lua-5.1.5 and running sile fails.

```
❯ sile simple.sil
This is SILE 0.9.2
<simple.sil>
Error detected:
/usr/share/sile/lua-libraries/bit32-compat.lua:26: attempt to call field 'mod' (a nil value)

❯ sile bibtex.sil
This is SILE 0.9.2
<bibtex.sil>
Error detected:
/usr/share/sile/packages/bibtex.lua:27: attempt to index local 'fh' (a nil value)
```

In 5.1 IMHO it's still fmod. Don't know lua that well (yet) but I think I read the change to math.mod was introduced in 5.3 together with an integer type. Am I correct?
When I change mod to fmod sile works (but it produces weird pdfs, because it uses different fonts and seems to mess up metrics).
Don't know how to deal with the bibtex error...

**Comment by simoncozens** [comment]
The first error is @pkulchenko's fault - we were 5.1 compatible before to change fd44282 . :-) Paul, any chance you could look into restoring 5.1 compatibility?

The default font in SILE is Gentium - the examples will look odd if you don't have that installed.

As for the bibtex error, that's because the bibtex package isn't very good yet. :-) Specifically it's not checking for file not found. If you go back a directory and run it as `sile examples/bibtex.sil` (or if you change the `\loadbibliography` command to `\loadbibliography[file=sample.bib]` you should get that working.

**Comment by alerque** [comment]
The path issue is related to #91 and a fix for that should alleviate the second part of this problem.

**Comment by ff2000** [comment]
Thx, amazingly fast responses here!
I am watching sile repo, so I remembered the discussion about relative paths. Error message really could be improved ;)
Going up one dir fixes showoff.sil, but not bibtex.sil:
```
❯ sile examples/bibtex.sil
This is SILE 0.9.2
<examples/bibtex.sil>
Error detected:
/usr/share/sile/lua-libraries/std/base.lua:10: bad argument #1 to 'pairs' (table expected, got nil)
```

Concerning the font: is it the "Original Gentium"? Because gentoo ships a "sil-gentium" which installs GentiumPlus.ttf - and pdf still look weird ;)
Nevertheless "Original Gentium" 1.03 installed from http://scripts.sil.org/gentium_download still looks slightly different, and there seems to be no proper Unicode support.
(Sorry for the OT...)

**Comment by alerque** [comment]
@ff2000 The `sile` compiler should be telling you about any font fall-back choices it is forced to make now (see #95 — and that might be a better issue on which to continue a discussion of not matching fonts). Are you running the HEAD version or the last 0.9.2 release?

**Comment by pkulchenko** [comment]
>> /usr/share/sile/lua-libraries/bit32-compat.lua:26: attempt to call field 'mod' (a nil value)
> The first error is @pkulchenko's fault - we were 5.1 compatible before to change fd44282 . :-) Paul, any chance you could look into restoring 5.1 compatibility?

@simoncozens, actually, the fix was supposed to improve compatibility ;) and I tested it on 5.1 as well. @ff2000, you seem to be running an older version of SILE as my copy of `bit32-compat.lua` (from the current master) has the following lines:

```lua
  local last = n % 2 --<-- line 24
  if(last == 1) then
   tbl[cnt] = 1 --<-- line 26
```

As you can see, there is something different on line 26 and there is no `mod` referenced anywhere in the file. BTW, there is no `math.mod` in Lua 5.1; you only get it if you turn on compatibility with Lua 5.0 ("Function math.mod was renamed math.fmod").

**Comment by ff2000** [comment]
Ah, I thought it was clear from sile output that I am using 0.9.2 release, but master still sets version to 0.9.2.
Just ran sile from git master (nice to not have to run make install :)) and the math.mod error is gone. Also I get warnings about missing fonts. Great!
Nevertheless the `bad argument #1 to 'pairs' (table expected, got nil)` error still exists. Should I report a seperate issue for that?

**Comment by pkulchenko** [comment]
Simon, this last issue (with `bad argument #1 to 'pairs'`) is related to the following code in `bibliography.lua`: `local t = std.table.clone(_ENV)`. When running with Lua 5.1, `_ENV` is not defined, so the clone call predictably crashes. I'm not sure what the intent here was, but I do see `_ENV` used in a couple of other places, which is not going to work for Lua 5.1 (so it does seem relevant to this ticket).

**Comment by pkulchenko** [comment]
@simoncozens, @ff2000, I fixed it with [this commit](https://github.com/pkulchenko/sile/commit/789df6dc2668cbfad49be8a036591db4d3a72d7b). Simon, it would be nice if you could review it; I'm fairly certain with my compat fix as I've been using something very similar in Mobdebug for a long time without any issues, but I'm not sure about `bibtex.lua` change as I don't see that `_ENV` being provided anywhere.

`bibtex.sil` example works as expected with the fix. if it all checks out for you, I can send a pull request.

**Comment by ff2000** [comment]
@pkulchenko  I can confirm that bibtex.sil compiles and the produced pdf looks as expected, so your commit fixes the problem.

**Comment by simoncozens** [comment]
@pkulchenko Had a look at your patch. I don't really understand it (insert standard rant here about Lua making massive incompatible changes between minor versions) but at the very least it's not working for me in 5.3 - in particular this bit of `bibtex.lua`

```lua
bibtexparser = epnf.define(function ()
  local _ = WS^0
```

The `WS` variable isn't found. The `epnf` module works by supplying an environment with a bunch of variables declared - see `inputs-texlike.lua`; I had my suspicions about your patch because you changed the use of epnf in `bibtex.lua` but not in `inputs-texlike.lua` when both are using the same mechanism. If I put the `_ENV` parameter back in, it works.

I modelled my bibtex style DSL on that approach.

**Comment by pkulchenko** [comment]
@simoncozens, you are right; I did mix the styles a bit and wasn't sure about that part.

I pushed another commit into [the same branch](https://github.com/pkulchenko/sile/tree/lua51-compat-env), which keeps the same style and restores the functionality for Lua 5.2+. I can't test it with Lua 5.3, but I'd expect it to work better. In the fragments I added, I only test for capabilities, not versions, which is the right way to do it.

Your approach was correct, but you missed `setfenv` call; you also seem to have `setfenv` added in a couple of places, so I removed one of them where I don't think it's needed.

I'll clean up/squash the commits before sending a pull request if the changes look good to you.

**Comment by simoncozens** [comment]
I've copied your branch into my repository and Travis should be doing a build on it now. If it works with 5.1 and 5.2 I'm happy for it to go in.

**Comment by pkulchenko** [comment]
Simon, sounds good; do you need me to send a pull request or are you good with the changes as is (and process them yourself)?

**Comment by simoncozens** [comment]
Well, so far on your branch, 5.1 passes tests, but 5.2 is showing the same problem as above: accepting the `_ENV` parameter was providing the `WS` variable, which is no longer declared.

**Comment by pkulchenko** [comment]
Hm, it should behave exactly the same as your original code; I think I returned providing tables to all places.

Actually, I think I missed one; one sec.

**Comment by pkulchenko** [comment]
Simon, somehow I indeed missed `_ENV` that I was planning to restore. Pushed another commit to [the same branch](https://github.com/pkulchenko/sile/tree/lua51-compat-env).

**Comment by simoncozens** [comment]
OK, got two green ticks from Travis, so I've merged that in. That should deal with the compatibility problems in this ticket. 

As for the bibtex package, the reason I marked it as *experimental* in the release notes is that it's undocumented and not guaranteed to work. (Or rather, it's undocumented because it's experimental and not guaranteed to work!) It needs a lot more working on before it's ready for people to use it. But at least tests pass now.

So I think we're done here - I haven't checked lua 5.3, because nothing has that in its package repository yet, but 5.1 and 5.2 work fine and 5.3 probably should.

**Comment by pkulchenko** [comment]
Simon; sounds good. Just one small note of caution: since you are doing automated tests anyway, you may want to include Lua 5.1 and Lua 5.2 (especially the latter) built with LUA_COMPAT turned off as this disabled handling of deprecated functions, which allows for the problems to surface sooner rather than later.
