### ISSUE TITLE
Remove Cairo/Pango output options (and hence dependencies).

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#104]
I know I'm late to the party so correct me if this is ignorance speaking, but…

It seems like there is some legacy code (and accompanying documentation, dependencies, etc.) being dragged around and I am unable to put my finger on why it needs to be there.

* The dependency chain is harder to get running on most platforms, and I don't know of any platforms where an included harfbuzz library won't be an option.
* The output is inferior.
* Having a second rendering chain to maintain is going to drag down new feature development.
* It's confusing to newcomers.

During transition I'm sure it made sense to keep the functional legacy rendering intact while the new one got worked out, but with harfbuzz being here to stay (it is right?) what is the point in dragging Cairo/Pango along for the ride?

**Comment by simoncozens** [comment]
Everything you say is true, and the code is already starting to rot, but I would like to keep it - or something like it - in the repository for architectural reasons. 

The reason being that SILE tries as much as possible to operate around the concept of separation of concerns between self-contained black box subsystems: you can replace the line breaking system with another algorithm and it shouldn't break the rest of the code; you can swap out the input system with another one which provides a similar abstract syntax tree, and everything still works (this is why I'm getting so worked up by bug #105, because the only way to solve it seems to be to break separation of concerns); and, of course, you can swap out the output system.

Implementing two or more different instances of the same subsystem is a great way to ensure that you are defining the interface of that subsystem well. Things which are common between multiple implementations are good candidates for moving into a common base class, and if it turns out that something is impossible, or only possible in one implementation, then you know you've got your abstraction points in the right place. 

And the end result of all *that*, apart from satisfyingly clean code, is that it's much easier to implement a new subsystem from scratch (which is not a theoretical concern - in the case of output systems, Paul K is putting SILE into a desktop application and using WxWidgets instead of PDF to render the output) if you have both very clean and clear interfaces *and* a couple of examples to work from, rather than if you are trying to replace the only existing implementation which is embedded deeply into the rest of the code.

So I think that, yes, it's yukky and a burden, but I think it provides sufficient architectural benefits that it should stay; if you're worried about the code rot, then either fix the rot by bringing it up to date, or implement another reference output system that can be kept up to date.

**Comment by alerque** [comment]
My viewpoint on this was entirely too narrow. Thanks for the explanation, and I agree what you have outlined is more important that the downsides I was thinking of. I was moistly thinking about the packaging hiccups involved in having conditional dependencies.

I think the answer to my concern is to suck it up on the packaging end and actually support both backends. The build system may need a bit of cleanup (perhaps support for a set of `--with <output plugin>` configure options) but based on this logic that sounds like that work should be done rather than avoided.

**Comment by alerque** [comment]
I was unable to find a reference to the work on a WxWidgets output system. Is that being done in public somewhere?

**Comment by pkulchenko** [comment]
@alerque, yes, I have the code running and working quite well for wxlua/wxwidgets. The only pending change for me is #114 (I'm still not sure why it's failing the CI build).

If you are interested, here is [the branch](https://github.com/pkulchenko/sile/tree/wxlua-output) that includes the currently working code. Note that the font substitution doesn't work well as the fonts are substituted based on font name without taking style into account (this should be fixed when #114 is merged).

You'll need to have wx.dll (or appropriate library for your platform); you can get it from [ZeroBrane Studio repository](https://github.com/pkulchenko/ZeroBraneStudio/tree/master/bin) (there are binaries for Windows, OSX (32bit), and Linux 32/64bit.

**Comment by alerque** [comment]
Thanks for the links @pkulchenko, I'll definitely be checking it out.
