### ISSUE TITLE
Rewrite diglot/parallel package

### ISSUE THREAD

**Issue by cyocum** [simoncozens/sile#107]
As a scholar who is working on texts in multiple languages, the diglot class *almost* works for my needs but I don't know enough about sile to make the necessary changes.  Maybe I can lean on the nascent community to help?

* Facing page with sync rather than parallel columns
* Document like structures (chapters, sections, etc). I tried to swap the plain class out for the book class but sile didn't like it.

Also there seems to be a bug? I have text of the left hand column appearing at the end of the right hand column.  Additionally, trying to use \being{left} .... \end{left} causes nothing to be output but no errors are produced.

I am using the 022ebb3abdd12590b16b2abaa61b48334751e90b commit at the moment.

**Comment by simoncozens** [comment]
The diglot class was written fairly early on in SILE's development, when I was more interested in "can I get SILE to do this?" rather than "what is the best way to achieve this and how will it interact with other components?" (and of course at the time I didn't know what the other components were going to be). I also assumed that people were going to be writing specific document classes in Lua for complex documents, which is crazy.

So it needs to be burnt down and then reborn as a package which can provide parallel text services to other document classes. This is very much on my mind - you're not the first to have problems using it - and I will be working on it soon.

**Comment by cyocum** [comment]
Ah, thank you very much for this!

**Comment by simoncozens** [comment]
This has been done in 42e9d73 and following; see `examples/parallel.sil` and `classes/diglot.lua`.
