### ISSUE TITLE
Brew formula for SILE

### ISSUE THREAD

**Issue by abbasmousavi** [simoncozens/sile#13]
Can you please make a brew formula for installing SILE on MAC?

**Comment by alerque** [comment]
I [just submitted](https://github.com/Homebrew/homebrew/pull/40893) a [basic working formula](https://github.com/alerque/homebrew/blob/sile/Library/Formula/sile.rb). I highly recommend installing from git at this point rather than the stable build. The PR should show up on any `brew search sile` or you can install it directly from my branch URL:

    brew install https://github.com/alerque/homebrew/blob/sile/Library/Formula/sile.rb --HEAD

**Comment by alerque** [comment]
After some rigmarole the SILE formula [has been accepted](https://github.com/Homebrew/homebrew/commit/e0c39f28735df2dcd654380ea489f355d3f6a34b). The usual `brew update` should get you the latest goodies including the ability to `brew install sile`. And if you are feeling brave and want to test the latest developments `brew install sile --HEAD` to install the latest git master branch code. (Note homebrew does not support upgrading head packages; to get the latest while in that mode you'll need to use `brew reinstall sile --HEAD`.)

**Comment by simoncozens** [comment]
Yay! Congratulations and many thanks!

**Comment by alerque** [comment]
You're welcome. But aren't you [supposed to be resting](https://twitter.com/simoncozens/status/612893001723985920)? Get out'a here ;-)
