### ISSUE TITLE
SILE fails if the whole file is text

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/sile#174]
Running a simple document like:

```tex
\begin[papersize=a4]{document}
\include[src=wb.txt]
\end{document}
```
(With [wb.txt](https://github.com/khaledhosny/aref-ruqaa/blob/master/tests/wb.txt) from aref-ruqaa tests), I get this error:
```
Error detected:
/home/khaled/.local/share/sile/lua-libraries/epnf.lua:142: stack overflow (too many captures)
```

**Comment by simoncozens** [comment]
I think I've fixed the actual bugs, but I haven't actually managed to get the document typeset yet. Sending 600,000 nodes through the line break algorithm is a good stress test :-)

**Comment by khaledhosny** [comment]
> Sending 600,000 nodes through the line break algorithm is a good stress test :-)

I actually want to set each word on a line of its own, but SILE does not have the equivalent of TeX’s `\obeylines`.

**Comment by simoncozens** [comment]
`SILE.settings.set("typesetter.parseppattern", "\n")` should do that for you. Try this:

```TeX
\begin[papersize=a4]{document}
\script[src=packages/verbatim]
\define[command=verbatim:font]{\font[language=ar,filename=arefruqaa-regular.ttf]}
\begin{verbatim}
\include[src=wb.txt]
\end{verbatim}
\end{document}
```

**Comment by simoncozens** [comment]
...actually that doesn't seem to quite work because of this line: ` SILE.settings.set("shaper.spacepattern", '%s')`.

If you define your own package which defines an `\obeylines` command to be `SILE.settings.set("typesetter.parseppattern", "\n")`, you should be fine. You can't quite do it inline at the moment because the backslash in `\n` is being interpreted as a command (bug #92).

**Comment by khaledhosny** [comment]
Both `verbatim` and the package idea work fine, I think I’m going to use the later as I will be using columns and may be other features.
