### ISSUE TITLE
Output outside frame

### ISSUE THREAD

**Issue by deepakjois** [simoncozens/sile#190]
This code:

```
\begin[papersize=a5]{document}
\script[src=packages/frametricks]
\nofolios
\set[parameter=document.parindent,value=0pt]
\font[family=Kohinoor Devanagari,style=Regular,language=hi,size=18pt]
गुलों में रंग भरे, बाद-ए-नौबहार चले
\showframe[id=content]
\end{document}
```

Produces this output. Note the rendering of text outside the frame.

<img width="674" alt="screenshot 2015-11-10 18 48 53" src="https://cloud.githubusercontent.com/assets/5342/11063324/c7d98d40-87db-11e5-91f2-b4f7943c081c.png">

Any clues? FWIW, I am seeing this only with the Devanagari fonts on OS X, not any others.

**Comment by alerque** [comment]
This does replicate for me on Linux copying the Kohinoor font files from a Mac.

**Comment by simoncozens** [comment]
OK, I understand this. Harfbuzz's opentype implementation doesn't know how to measure a glyph's descender. But Behdad has convinced me that I don't need to and that there are better ways of handling linespacing than TeX's height/depth algorithms. This is happening within the `linespacing` package, which implements nearly everything apart from the positioning of the first baseline on the page.

**Comment by simoncozens** [comment]
No, this is a bit more complicated than I thought. `y_bearing` and `height` are both coming out of `hb_font_get_glyph_extents` as zero for Indic, but not for Latin. It *will* be fixed when we move to the new linespacing package, but I am not sure why it's broken now. @behdad?

**Comment by simoncozens** [comment]
Oh, I don't understand. `hb-shape` with OT funcs is not showing any extents for Latin *or* Indic, but SILE is correctly getting heights and depths for "abc" from *somewhere* anyway.

**Comment by simoncozens** [comment]
```
> makenodes("abc गुलों", { family="Kohinoor Devanagari"})             ..""
N<14.0380859375pt>^7.568359375-0.146484375v(abc)
G<2.642578125pt plus 1.10107421875pt minus 0.73404947916667pt>
N<6.6064453125pt>^0-0v(गुलों)}"
```

"abc" has height and depth, गुलों doesn't. Same algorithm used to get both.

**Comment by behdad** [comment]
> "abc" has height and depth, गुलों doesn't. Same algorithm used to get both.

CFF font versus TrueType?  Is this the algorithm using glyph bounds?

**Comment by deepakjois** [comment]
Kohinoor Devanagri is listed as an ‘OpenType Postscript’ font. So that makes it a CFF font. 

There is a code-path in `justenoughharfbuzz.c` [here at the latest commit on master](https://github.com/simoncozens/sile/blob/0323810e398a4a2124b8d10f44fa4c6a0a6342f1/src/justenoughharfbuzz.c#L142):

```
    /* Harfbuzz's support for OT fonts is great, but
       there's currently no support for CFF fonts, so
       downgrade to Freetype for those. */
    if (strncmp(font_s, "OTTO", 4) == 0) {
      hb_ft_font_set_funcs(hbFont);
    } else {
      hb_ot_font_set_funcs(hbFont);
    }
```

This is before `hb_font_get_glyph_extents` is called. So is that the problem then?

**Comment by simoncozens** [comment]
That's basically it. The final piece of the puzzle is that Kohinoor is a TrueType Collection. So it's a CFF font - so we should use the Freetype functions - but because it's a TTC, it doesn't start with the "OTTO" tag at the beginning of the file. So the wrong functions are being picked up here.

I've extended the comparison to also use Freetype when dealing with a TTC. It wouldn't be too hard to sniff around in the data and extract the sfnt header for the appropriate font within the collection, but I can't immediately do that with `get_table` and it doesn't actually *matter* if we use Freetype - it's just that the OT functions are faster. So it just avoids a possible optimization.

Anyway, again the *proper* fix is to use typoAscender to set the position of the first line, and I'm hoping to get that done soon.

**Comment by khaledhosny** [comment]
Passing `HB_TAG_NONE` to `hb_face_reference_table` should give you the whole font (or you can use `hb_face_reference_blob` which does the same).
