### ISSUE TITLE
error loading module 'lua-utf8'

### ISSUE THREAD

**Issue by no-vici** [simoncozens/sile#1920]
Compatibility issues with `lua-utf8` have forced me to downgrade `SILE` to `SILE v0.14.9 (Lua 5.4)` after each system update. Has anyone else experienced this problem?

```
Your sile document is being processed...

/usr/bin/luajit: error loading module 'lua-utf8' from file '/usr/lib/lua/5.4/lua-utf8.so':
	/usr/lib/lua/5.4/lua-utf8.so: undefined symbol: lua_callk
stack traceback:
	[C]: at 0x7f15fe737d70
	[C]: in function 'require'
	/usr/share/sile/core/sile.lua:24: in main chunk
	[C]: in function 'require'
	/usr/bin/sile:26: in main chunk
	[C]: at 0x55c110f25cd0
lua: ebook-builder-v0.lua:110: Command failed: sile Diary_of_Saigon_1975.sil
Exit: exit
Status: 1
...
```

**Comment by alerque** [comment]
What OS are you an and what install methods are you using for Lua Rocks and SILE?

Also why are you using Lua 5.4 specifically? It will still work of course, but we've switched the default/recommendation to LuaJIT because it is just *so much* faster.

**Comment by alerque** [comment]
Something doesn't add up there. The Manjaro packages are just going to be copies of the Arch Linux packaging, which I build. The default Lua used for the Arch packages is LuaJIT, so installing `pacman -S sile` should get you a LuaJIT package and a bunch of `lua51-*` packages for the LuaRocks dependencies. This should include `lua51-luautf8`.

The error messages you are showing in your first post however are showing an a version of SILE that is build against Lua 5.4. You appear to have mixed and matched packages somehow. I don't know what your "downgrade" process is (since no such thing is really supported in Arch/Manjara) but I believe you have cross wired something and are not really using the packages & their dependencies as they were built.

I suggest a `pacman -Syu` to get everything freshened up into a supported fully updated set, then lets look at `pacman -Qi sile` to understand which build you have, `sile --version` to review what SILE thinks it is build against, and perhaps `sile -e 'SU.dump(pl.stringx.split(package.path, ";"))' -e 'os.exit()'` to have a look at the module loader paths that got configured.

**Comment by alerque** [comment]
Two other things to confirm: have you ever done an installation from source too or just the system package manager? Are you by chance trying to run SILE from inside a checkout of the SILE sources?

**Comment by alerque** [comment]
First, the output of the path dump I requested above would be useful:

```console
$ sile -e 'SU.dump(pl.stringx.split(package.path, ";"))' -e 'os.exit()'
```

Also `which sile` might suggest if you're actually running the system installed SILE package.

**Comment by alerque** [comment]
It looks to me like you somehow have a partial SILE install in your personal user's home directory, possibly installed with `luarocks install sile`. Possibly those fragments are just from resilient or some other 3rd party library. Something about those is probably cross wired with SILE itself. In particular to use 3rd party modules you need to install them using the same version of Lua as SILE uses. But even with something from a different Lua version installed on the system or in your home user, that doesn't explain why running SILE is *finding* the wrong bits.

Do you have anything in your user's shell RC files for using local rocks? Fore xample `eval $(luarocks path)` or anything along those lines?

**Comment by alerque** [comment]
You can install the Resiliant library with a matching Lua version. I'll lookup the command later but it is probably something like `luarocks --lua-version 5.1 install --local`, and then you can add your paths with something like `eval $(luarocks --lua-version 5.1 patch --local)`. However I haven't tested that so the exact command might vary. Also instead of using `--local` for this I would actually recommend using `--tree lua_modules` or something like that and install the Rocks local to your project. Installing them to the system or your user makes for trouble when you want to run a project that does *not* use those modules because silex kind of aggressively takes over some core SILE functions. SILE is designed so that you *can* override its internals, but that comes at the cost of playing with fire. By only installing it locally to a project and only updating your patch to the modules when using it you'll eliminate some of that pain.
