### ISSUE TITLE
Need package for preparing press-ready sheets with crop marks

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#196]
SILE needs a package that sets up trim and bleed sizes and arranges typeset pages onto larger press sheets and adds the appropriate crop marks.

**Comment by simoncozens** [comment]
So, this is going to be a package which changes the output PDF text size. The problem at the moment is that the outputter's `init` method is called when the document class is all set up in `baseClass.init`, and that fixes the PDF page size. So the first task to make this happen is to rewrite the outputter to call `init` itself before trying to output anything if `started` is false, instead of calling `init` explicitly in baseclass.

Then a `cropmarks` package will:

* Increase `SILE.documentState.paperSize` to the required paper size.
* Offset the `page` frame in the document template.
* Invalidate and recalculate all frames for the first page.
* Add something in the `endPage` method of the class to draw the marks.
