### ISSUE TITLE
verbatim doesn't obey spaces

### ISSUE THREAD

**Issue by mhosken** [simoncozens/sile#258]
If a line starts with spaces they are ignored in verbatim. Patch enclosed
[fixverbatim.txt](https://github.com/simoncozens/sile/files/104422/fixverbatim.txt)

**Comment by alerque** [comment]
Hey Martin. I took your patch above and rebased it against the current git HEAD version so that it applies. The result is in my [fix-verbatim](https://github.com/alerque/sile/tree/fix-verbatim) branch if you'd like to test it. I'm also opening it as a PR so that we can see how the tests  do but we could probably do with a test specific to this behavior. Do you have a small example of this that we can run with and without the code applied to test that it's working as expected?

Also can I inquire as to why you used an integer instead of a Boolean value for this flag?

**Comment by mhosken** [comment]
Dear Caleb,

> Hey Martin. I took your patch above and rebased it against the current git HEAD version so that it applies. The result is in my [fix-verbatim](https://github.com/alerque/sile/tree/fix-verbatim) branch if you'd like to test it. I'm also opening it as a PR so that we can see how the tests  do but we could probably do with a test specific to this behavior. Do you have a small example of this that we can run with and without the code applied to test that it's working as expected?

I don't. But anything with line initial spaces (e.g. a code sample with indentation) would make a good test.

> Also can I inquire as to why you used an integer instead of a Boolean value for this flag?

I would love it to be boolean, but my knowledge of lua is too low to do the right thing there. Please feel free to fix it to a bool.

TIA,
Martin
