### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/sile#294]
http://www.sile-typesetter.org/examples/ has no images or CSS, and /what-is/ has no CSS.

**Comment by alerque** [comment]
Ug. I see what the problem is. I switched to relative paths for resources so that the site could be tested locally and/or on people's Github forks to see if it was working before merging changes. It looks like the Jekyll templates don't (yet) have the wiring to add the base path to pages generated outside of the root directory. I'll have a look.

**Comment by simoncozens** [comment]
Thank you!
