### ISSUE TITLE
[META] Chat and forum to ask questions

### ISSUE THREAD

**Issue by suhr** [simoncozens/sile#325]
Maybe [Gitter](https://gitter.im/) and [Discourse](http://www.discourse.org/).

**Comment by alerque** [comment]
A couple of us have occasionally hijacked the Typesetting channel on the [Bible Technology Slack](http://bibletechnology-slack.herokuapp.com/) for SILE discussions, but I agree a more general purpose solution would be better. I think Gitter is a great idea and would be happy to join in there. If people prefer I could also host a Mattermost instance.

I'm not so sure about Discourse. I agree it's a much better solution than the current Google Groups arrangement, but I'd like to see the forum situation consolidated rather than fragmented and I don't know if we have a good feel for what the actual need is here. Maybe Discourse is the best route to take it and shut down the other channels, but maybe there are more specific needs?

I've also been thinking about proposing via a meta post that SILE be on topic for the [TeX Stack Exchange](http://tex.stackexchange.com/). It would be a bit of a direction change for that site, but it might actually work. If not, that would make SO the other reasonable place to ask usage questions, but I think the typesetting expertise in general and similarity in purpose (and even implementation) would make the TeX site a better home if we could convince the old timers we're not heretics. Thoughts?

**Comment by simoncozens** [comment]
Thanks for adding Glitter. We'll see how that goes. I have been pretty rubbish at responding to mailing list mails, and I apologise for that. I don't think you'll get very far with TeX.SE, but it can't hurt to ask.
