### ISSUE TITLE
Two columns bible class broken

### ISSUE THREAD

**Issue by gnodet** [simoncozens/sile#326]
I'm very new to Sile and I'm trying to get a 2-columns bible, but the HEAD usx example fail when I switch to 2 columns.

**Comment by gnodet** [comment]
After fixing #328 , here's the error printed:
```
Error detected:
RequiredFailure {description=A required constraint cannot be satisfied}
```

It happens during the call to `switchMaster`.

**Comment by simoncozens** [comment]
I've fixed *this* particular bug with the Bible class. There are still two known issues outstanding. (One is about footnotes which appear in text in the right column, but that's a tricky issue, and that's why most two-column text doesn't have footnotes within the columns; one is the balanced column bug #118)

**Comment by gnodet** [comment]
Thx, also, the grid layout does not seem to work on the same example usx 049EPH, the lines are not aligned in the two columns.  Do you want me to raise an issue for it ?

**Comment by simoncozens** [comment]
This is also the balanced column bug in disguise. If you comment out `self:loadPackage("balanced-frames")` in bible.lua, and uncomment the `\grid[spacing=14pt]` line in usx.sil, you'll get a grid-aligned Bible.
