### ISSUE TITLE
OS X language="xx" Errors

### ISSUE THREAD

**Issue by runeimp** [simoncozens/sile#370]
I decided I didn't want to let SILE hyphenate words at all for my resumé and according to sile-0.9.2.pdf I could add `language="xx"` to my font call. But that results in:

```
$ sile mpg-resume.xml
This is SILE 0.9.4
<mpg-resume.xml>

! Error loading language xx: /usr/local/Cellar/sile/0.9.4/share/sile/core/sile.lua:62: module 'languages/xx' not found:
	no field package.preload['languages/xx']
	no file 'languages/xx'
	no file 'languages/xx.lua'
	no file 'languages/xx.lua'
	no file '/usr/local/Cellar/sile/0.9.4/share/sile/languages/xx.lua'
	no file '/usr/local/Cellar/sile/0.9.4/share/sile/lua-libraries/languages/xx.lua'
	no file '/usr/local/Cellar/sile/0.9.4/share/sile/lua-libraries/languages/xx/init.lua'
	no file 'lua-libraries/languages/xx.lua'
	no file 'lua-libraries/languages/xx/init.lua'
	no file '/usr/local/share/lua/5.2/languages/xx.lua'
	no file '/usr/local/share/lua/5.2/languages/xx/init.lua'
	no file '/usr/local/lib/lua/5.2/languages/xx.lua'
	no file '/usr/local/lib/lua/5.2/languages/xx/init.lua'
	no file './languages/xx.lua'
	no file '/usr/local/lib/lua/5.2/languages/xx.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './languages/xx.so'
	no file 'core/languages/xx.so'
	no file '/usr/local/Cellar/sile/0.9.4/lib/sile/languages/xx.so'
```

With the error repeated for ever font call. I checked and there is no `xx.lua` in my `/usr/local/Cellar/sile/0.9.4/share/sile/languages` folder. If it obvious by the last sentence SILE was installed via Homebrew. Also this happens weather I use an `.XML` or `.SIL` source.

**Comment by simoncozens** [comment]
It's been changed to `und` (which is the correct ISO code), but we need to update the docs.

**Comment by alerque** [comment]
I updated the documentation in 54f9cb4. Although the documentation PDF in the repository was not rebuilt prior to the last release, it has been updated three times since that commit, so it should have this update in it. I'm not sure where @runeimp got the miss-matched documentation PDF but the one in the repository should document the current expected behavior.

**Comment by alerque** [comment]
@runeimp The PDF you were looking at was probable the one off of the SILE website rather than the one that came with the package (as evidenced by the filename it was for 2 versions behind what you were actually using). For future reference the cover page should also state which version it is for. Please note that for `X.Y.Z-unreleased` versions of SILE such as what you are running even the latest PDF in the repository may not be up to date and the best way to grantee that you have documentation that matches your program is to build a manual PDF yourself from the same version of the code as what you are running.

In the mean time I have updated the website so that the manual link takes you to at least the last released version.
