### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by xor256** [simoncozens/sile#381]
Is possible to add Ruby to SILE?

**Comment by simoncozens** [comment]
Do you mean Ruby the programming language (no, it's not; SILE is written in Lua.) or Ruby the Japanese _furigana_? (Yes, it is, see the `ruby` package.)

**Comment by xor256** [comment]
I thing about Ruby language as additional language not main.
For example i thing about creating packages in ruby similar in Lua or C.

Interface to run ruby or mruby is very simple. In C executing code in ruby is 10-15 lines.

**Comment by alerque** [comment]
@xor256 SILE isn't written in C. It's written in Lua. Writing packages and adding scripts to SILE documents in Lua makes sense because you are just extending the existing code structures. It isn't some patched on API or interface, it is first class code along with the core typesetter.

You can call out from Lua to any language or command you want, but the responsibility for doing that is on you, not on the typesetting engine itself.

**Comment by xor256** [comment]
is possible writing code in C runing from Lua.
