### ISSUE TITLE
libtexpdf is GPLv3, which is legally problematic for an MIT SILE

### ISSUE THREAD

**Issue by chris-morgan** [simoncozens/sile#392]
As far as I can tell, libtexpdf is the only serious outputter for SILE. The problem is, libtexpdf is GPLv3, which the MIT is not compatible with. Distributing SILE as source, saying “you can link with libtexpdf if you want, or use some other backend” is legally OK, but distributing SILE as a binary with libtexpdf in it (and SILE is clearly a derived work for the purposes of the license) is probably illegal—at best, it’s dubious.

There are two options I see:

1. Relicense libtexpdf as MIT, if possible;
2. Replace libtexpdf with some MIT-licensed software.

As it is, I can’t embed SILE in an MIT-licensed piece of Bible software that I’m planning unless I rip out libtexpdf and replace it with another backend.

**Comment by simoncozens** [comment]
Oh man. This is huge. :(

libtexpdf is a derived work from TeX Live's dvipdfm-x, which is outside my control. It's been GPL'd since 2002. So option 1 is not possible.

I'm not happy about option 2. There is no better PDF library right now, under any license.

I'm really not sure what to do. I think *I*'m OK, because I am not distributing SILE as a binary, although I am not sure if it is allowable to ship a copy of libtexpdf with the SILE source distribution (which is what I'm doing). But clearly *you're* not OK. I guess you will have to write your own backend to a MIT-licensed PDF engine, if you can find one.

I'd like to hear input from others on this, particularly those with license compatibility experience: @khaledhosny, @alerque, @pkulchenko?

**Comment by khaledhosny** [comment]
For the licensing part I think only professional legal advice would count here, so I have nothing to say (except may be pointing that it is not clear, for me at least, if SILE use of libtexpdf counts as linking or aggregation in GPL terminology).

As for replacements, I don’t know much. I have seen http://pdfhummus.com/ (https://github.com/galkahana/PDF-Writer) a while ago and it seemed to have good API and features from a quick glance, but I never used it.

**Comment by pkulchenko** [comment]
> distributing SILE as a binary with libtexpdf in it (and SILE is clearly a derived work for the purposes of the license) is probably illegal—at best, it’s dubious.

IANAL caveat, but I'm not sure that's the case after reading [A Practical Guide to GPL Compliance](https://www.softwarefreedom.org/resources/2008/compliance-guide.html) and other sources. Section 4.1 is specifically about binary distribution permission and lists several options that may work for SILE: 

> 4.1.1 Option (a): Source Alongside Binary
> GPLv2 § 3(a) and v3 § 6(a) embody the easiest option for providing source code: including Corresponding Source with every binary distribution. While other options appear initially less onerous, this option invariably minimizes potential compliance problems, because when you distribute Corresponding Source with the binary, your GPL obligations are satisfied at the time of distribution. 

It seems like "corresponding source" refers to libtexpdf in this case, although I can see how the definition of "corresponding source" may also refer to the entire SILE code: "The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities."

> 4.1.4 Option 6(d) in GPLv3: Internet Distribution
> If distribution of executable or object code is made by offering access to copy from a designated place, then offering equivalent access to copy the source code from the same place counts as distribution of the source code, even though third parties are not compelled to copy the source along with the object code.
> When that was written in 1991, Internet distribution of software was the exception, not the rule. Some FTP sites existed, but generally software was sent on magnetic tape or CDs. GPLv2 therefore mostly assumed that binary distribution happened on some physical media. By contrast, GPLv3 § 6(d) explicitly gives an option for this practice that the community has historically considered GPLv2-compliant.
> Thus, you may fulfill your source-provision obligations by providing the source code in the same way and from the same location. When exercising this option, you are not obligated to ensure that users download the source when they download the binary, and you may use separate servers as needed to fulfill the requests as long as you make the source as accessible as the binary.

**Comment by simoncozens** [comment]
OK, having got some advice from license wranglers, I think there isn't a problem here.

1) GPL and MIT licenses are compatible.
2) If you link to a GPL licensed library, you need to release your code under a GPL-compatible library.
3) See 1).

**Comment by chris-morgan** [comment]
@simoncozens I believe your first point is imprecise: Yes, MIT is GPL-compatible, but that means GPL software can integrate MIT software, *not* the other way around. That then invalidates the second. So I think this should still be an open issue.

**Comment by simoncozens** [comment]
I don't really want to get into a protracted argument about this, because I'm only passing on the advice that I have received.

But 1) licenses put restrictions on people, not software. If the people involved are complying with the terms of both licenses for the pieces of software in question, we're all good. I'm doing that in distributing `libtexpdf` under the terms of the GPL.

2) In source format, no "integration" is taking place. The sources are clearly distinct. So there is nothing problematic about this repository at all. (The same is true of XeTeX, which uses the same licenses for the same things.)

3) When the sources are linked (i.e. in binary format), anyone who releases the resulting binaries must comply with the terms of the GPL. (This is not the same as saying that the binaries must be released under the GPL; see 1). I'm not releasing binaries, but if you are, then you will need to also distribute sources for libtexpdf. Which is not exactly onerous.

I'm happy with the advice I've received from some of the top guys on debian-legal, and I've concluded this isn't a problem for SILE. I'm a bit unhappy about leaving it this way because the whole point of choosing a permissive license for SILE was to allow people to do what they want with it, but 

1) I think you're going to be fine, but if you have still suspicions about whether or not you can use libtexpdf in your project, you probably need to consult a lawyer yourself.

2) if having consulted a lawyer you realise you're not fine, please feel free to find a MIT-compatible PDF generation library. I tried libharu but last I looked it does not allow you to place glyphs by ID.

Good luck!

**Comment by alerque** [comment]
**Caveat**: The following post belongs at the top of the thread. I wrote it the other day but forgot to post before I left my desk. As such it doesn't take into account the ongoing discussion.

----

Hey @chris-morgan, thanks for bringing this up. I'm not an expert in licensing and this is definitely a sticky issue without a clear cut solution. That being said I'm not entirely convinced you have a problem.

MIT is pretty permissive, whereas the GPL is strict copy-left. It's commonly assumed (and it's an industry standard 'safe' presumption) that you can't _integrate_ GPL code into MIT projects, but various arrangements of using them side by side, having dependencies, or linking to it is harder to pin down. There isn't actually a legal precedent for it leaving some gray area for projects with _more_ permissive licenses. The restriction made by the GPL is specifically linking into proprietary programs.

> This General Public License does not permit incorporating your program into proprietary programs.

Your project, being MIT, is not proprietary. If you were to make sure and note the included project's license and make the source code available, I think you'd be on reasonable (if not legally proven) ground. This specifically isn't good enough for a proprietary project that wanted to embed some GPL library, but in your case you would also (presumably) be posting the MIT licensed source for your project. The net result relative to the GPL based code would that anybody who wanted to use the code for your integration (the derivative) would be able to do so under the terms of the GPL because your MIT code _can_ be integrated the other way around.

Like I said this isn't cut and dry, but as along as you are making the source for your project available (not binary-only distribution) and your derivative would could be used inside GPL projects (as MIT code can be) then this doesn't seem to be a violation of the license.

Of course a much cleaner way would be if the upstream project already had a [linking exceptions](https://en.wikipedia.org/wiki/GPL_linking_exception). One thing to look into is whether dvipdfm-x has ever been or could be licensed with the  class path exception or under a form of the LGPL. This would make it easier on downstream projects wanting to include it as a library and pretty much solve your issue.

As long as you are distributing the code of your project under MIT alongside any binaries you may produce and noting the respective part of the code base that is GPL rather than MIT then I don't think you have an issue.

One last thing for you to consider is setting up your project to be dual licensed. Dual licensing is a pain, but as long as all contributors agree to both licenses it can usually be done. This would alow you do do a binary only version of your app sans the pdf output path that could be distributed and used without any source code sharing restrictions and a version with that module that needed to be distributed along with source to comply with the GPL.
