### ISSUE TITLE
Consider using luabidi

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/sile#397]
https://github.com/deepakjois/luabidi is a pure Lua implementation of the Unicode Bidirectional Algorithm, and should be a more conformant implementation than the one we are currently using.

**Comment by alerque** [comment]
It looks like the author of that Lua library @deepakjois has previously contributed to SILE, but the Bidi library is a new project and didn't exist when Simon was hacking on this. Using a standardized and conformant implementation of this  would certainly be a good thing. I know [it was discussed](https://github.com/simoncozens/sile/issues/173#issuecomment-134559681) that we're currently mostly doing the right thing, but using a full implementation of the spec instead of hacks that cover current known cases can only be a good thing. 

This discussion should go along with the one about using ICU directly (#173).

**Comment by deepakjois** [comment]
Although luabidi itself is pure Lua, one of its dependencies [luaucdn], is a Lua binding around [ucdn], which is a C library. So now I am wondering if it is fair to claim that luabidi is a _pure_ Lua implementation of the BiDi algorithm.

All the dependencies are installabale via LuaRocks though.

[luaucdn]:https://github.com/deepakjois/luaucdn
[ucdn]:https://github.com/grigorig/ucdn

**Comment by simoncozens** [comment]
...at which point it may be better to use ICU.

**Comment by khaledhosny** [comment]
ICU would be my first choice of course, but we can abstract the luacdn dependency if needed since we already have a stripped down UCD of sorts for the current bidi implementation.

**Comment by simoncozens** [comment]
We're already at the point where SILE gives differing input when you have ICU and when you don't. I'm now toying with the idea of making ICU a hard requirement, in which case, handing off bidi to ICU becomes more desirable. Any reasons why I shouldn't?

**Comment by khaledhosny** [comment]
ICU should be fine, its implementation is up to date and should be conformant, LibreOffice/OpenOffice, Java use it and I think Firefox is switching to it as well, so we should be in good company.

**Comment by simoncozens** [comment]
We now use ICU for bidi - at least for getting the levels. Reordering is still done internally because ICU only works on text, and we need to maintain node information.
