### ISSUE TITLE
OS-X: Building from source

### ISSUE THREAD

**Issue by clintolsen** [simoncozens/sile#456]
Hi:

I was wondering if there are any special switches necessary to generate configure etc. I do have automake installed from ports and brew, but I get errors when trying to run automake.

Thanks,

-Clint

**Comment by alerque** [comment]
First of all you are aware that you can compile and install from the latest master branch using `brew install sile --HEAD` right? Just checking.

That being said if you want to compile from your own source location there shouldn't be much you need to specify unless you have non-standard paths for things like the Lua interpreter. You might have a look at [the homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sile.rb) for ideas. Specifically the install block on L28–37 show the sequence of commands run to install from source.  Also make sure you have the prerequisites listed there.

If that doesn't help, let us know more specifically what errors you are seeing.

**Comment by clintolsen** [comment]
No, I didn't know about that. Is this written somewhere in the docs?

So, trying to install this version caused it to bitch about the fact I have MacPorts installed. I don't think this is going to be easily fixable. It suggested I do:

<pre>checking for required Lua library zlib... not found
configure: error: cannot find Lua library zlib - install from luarocks package lua-zlib

READ THIS: http://docs.brew.sh/Troubleshooting.html


Error: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports
</pre>
 
I'm relatively new to brew, so I'm not about to wipe my MacPorts to enable this.

I'll try going through the recipe to see if it's easy to replicate.

**Comment by alerque** [comment]
On that case dispense with `brew` and just do it from source. You'll just need the right prerequisites and path to Lua and friends. There should be enough information in that formula to clue you in on how to run `./configure`.

The `--HEAD` thing is a standard way of using `brew` to install from source master branches rather than the last release version. It's documented as part of Homebrew and I believe it's mentioned in the SILE docs or somewhere in previous issues on this. However I haven't been pushing the use of Homebrew much in the documents because they still haven't really fixed the Lua dependency issues which it doesn't handle for you as could be expected.

We could probably setup a Macports package as well. I've never used Macports and the old iMac I have hanging around  for testing is currently dead so I can't really do this right now but I can't image it would be that difficult to setup a package for that system. Who knows, it might even handle the Lua issues better than Homebrew.

**Comment by clintolsen** [comment]
I would love to dispense with brew. How can I find out where it's building things and how to see the error messages? These opaque systems are really annoying. I tried running `install --debug` and I can't even get a directory name where I can find this stuff being built.

**Comment by clintolsen** [comment]
OK, I see that if I exit to shell, I can examine the build contents. Digging...

**Comment by clintolsen** [comment]
I was able to get brew to work. For whatever reason I didn't have the `lua-zlib` package installed under luarocks.

<pre>$ which sile
/usr/local/bin/sile
$ sile -v
This is SILE 0.9.5-unreleased

! Could not find file at -v
</pre>

**Comment by simoncozens** [comment]
That looks good. We should probably support a `-v` flag. :-)
