### ISSUE TITLE
What are the valid xml tags and formats?

### ISSUE THREAD

**Issue by kstenerud** [simoncozens/sile#470]
I can't find a list of allowable xml tags in the documentation. Is there a list of which sile commands are allowable in xml and what form they have? `img` isn't allowed, for example:

    ! Unknown command img at book.xml l.4, col.47

from:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<sile class="book" papersize="6in x 9in">
  <font filename="book/fonts/GoudyOldStyleBT-Roman.otf" size="12pt">
    <chapter name="A chapter">This is a test!!<img src="book/graphics/separator.png"/>
    </chapter>
  </font>
</sile>
```

I'm also not sure if chapter is correct. The sile command `\chapter` has only an unnamed default attribute. I'm using `name` as the xml attribute, but that's just a guess.

**Comment by simoncozens** [comment]
Hello Karl. The XML tags are completely equivalent to the "TeX-like" markup. So where the documentation uses:

```TeX
\chapter{This is a test}
```

you can say

```XML
<chapter>This is a test</chapter>
```

The reason `<img>` doesn't work is because it requires the `image` package to be loaded:

```XML
<script src="packages/image"/>
<img src="..."/>
```

Essentially, just like in the TeX-like format, all tags are valid so long as their meaning is defined somewhere: `<chapter>` is defined in the book class, and `<img>` is defined in the image package.

**Comment by kstenerud** [comment]
Beautiful! Thanks!
