### ISSUE TITLE
Image appears before text when img command comes after text

### ISSUE THREAD

**Issue by kstenerud** [simoncozens/sile#471]
Given the following document:

```
\begin{document}
\script[src=packages/image]
Here is some text!
\img[src=separator.png, width=100%fw]
\end{document}
```

The output is:
![screen shot 2017-06-03 at 2 32 58 pm](https://cloud.githubusercontent.com/assets/245857/26757189/9cdb03da-4869-11e7-8dba-061c94895f85.png)

There are a couple of problems:

1. The image is appearing BEFORE the text
2. The image is showing up indented, and running off the edge of the page (ideally I'd want it centered)

**Comment by simoncozens** [comment]
The image and the text are appearing on the same line. Maybe add a \par command after the text, or use a blank line to start a new paragraph, like this:

```TeX
Here is some text!

\img[src=separator.png, width=100%fw]
```

Note also that paragraphs have an indentation applied to them by default. If you don't want your image to be indented, say:

```TeX
Here is some text!

\noindent\img[src=separator.png, width=100%fw]
```

**Comment by alerque** [comment]
Simon's explanation is spot on for how to do this, but just in case it wasn't clear what happened, in your example the image is not actually coming _before_ the text. The paragraph is being built up with items that get typeset from left to right. The text is getting spit out first, then the image. Because the image is aligned to the baseline of the text, the line height for that line is being expanded to fit the image. The text that you see on the left is on the same baseline as the image, and the text is before the image.

Stuffing an object that is 100% the width of the frame into the middle of a paragraph that already has horizontal items (words) is going to cause a frame overflow condition as the line breaker cannot find any location to break the text inside it's allowed constrains (such as being able to stretch spaces).
