### ISSUE TITLE
Inserting content into vbox, but nothing is displayed

### ISSUE THREAD

**Issue by kstenerud** [simoncozens/sile#473]
I have the following code to create a vbox and inject some paragraphs:

```lua
  SILE.typesetter:leaveHmode()
  SILE.call("supereject")
  SILE.call("center", {}, function()
    SILE.call("vbox", {}, function()
      SILE.call("img", {src="book/graphics/separator.png", width="100%fw"})
      SILE.call("break")
      for _, filler in ipairs(SILE.scratch.fillers[SILE.scratch.currentFillerIndex]) do
        for _, paragraph in ipairs(filler) do
          SILE.typesetter:typeset(paragraph)
          SILE.call("medskip")
        end
      end
      SILE.call("img", {src="book/graphics/separator.png", width="100%fw"})
      end)
  end)
```

If I take the vbox call out, it displays fine (although at the top of the page - I want it all centered vertically). With the vbox call in, all I get is an empty page.

**Comment by alerque** [comment]
What do you expect the `vbox` to accomplish in this context?

**Comment by alerque** [comment]
@kstenerud I'm unable to figure out what you are trying to accomplish here. I'm taking a stab and guessing that your fillers array is just some sort of generic content and that you're trying to put an image and a paragraph or two about it on a page with the whole combination  being centered vertically.

In that event this might work (note I've used content available from the SILE repository so if you run this from a test file there it will work, otherwise replace with your images and content.

```Lua
SILE.require("packages/image")
SILE.require("packages/lorem")
SILE.typesetter:leaveHmode()
SILE.call("supereject")
SILE.call("hbox")
SILE.call("vfill")
SILE.call("center", {}, function()
    SILE.call("img", {src="documentation/gutenberg.png", width="50%fw"})
    SILE.call("break")
    SILE.call("lorem", { words = 80 })
end)
SILE.call("vfill")
SILE.call("break")
```

![selection_427](https://user-images.githubusercontent.com/173595/33561143-eaf785c6-d922-11e7-905f-6bafa5b738b3.png)


If that isn't what you're after please explain a little better what you're trying to accomplish and we'll try to help you out.

**Comment by kstenerud** [comment]
I was expecting it to behave like a column, adding things one below the other, into a structure (vbox) that will be centered on the page.

The separator was a flourish. I was trying to do some text centered horizontally, bounded by two flourishes:

![flourish](https://i.stack.imgur.com/j5AaI.png)
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
![flourish](https://i.stack.imgur.com/j5AaI.png)

(All centered horizontally, of course)

**Comment by alerque** [comment]
Hey @kstenerud I think I see what you were trying to accomplish...and it's easy enough to do, `\vbox` just isn't the command to do it with.

Every page in SILE get's "filled up". By default the page end route adds as flexible `\vfill` that takes up as much vertical space as needed to fill up the page. Based on that knowledge  here are some tips:

1. If you wanted to typeset content at the bottom of a page you will need to disable that filler (possibly by breaking the page yourself with `\par\break` or similar). That way everything doesn't get pushed to the top by the filler content. Next you'll want to add a vertical filler to the _TOP_ of the page. The trick here is that you can't add vertical space to a page until you have content on it because the page building will eat excess vertical space at page breaks, so you need to start your page with `\hbox\vfill`.
1. If you want to center content on a page, you can keep the `\vfill` at the end of the page, but you need to add one at the beginning of the page with the same stretch properties. When the page layout routine runs it will balance the stretchable spaces so they each get an equal share of the excess, thus centering your content.

You don't need `\vbox` because your content _already_ behaves as a column as you want it to (and the vbox structure introduces some complications/limitations that you don't need). All you need to do is start your page with the vfill and let the default page break mechanism end the page.

```Lua
SILE.call("hbox")
SILE.call("vfill")
SILE.call("center", {}, function()
  -- code to output flourish here
  -- code to output paragraphs here
  -- code to output flourish here
end)
```

If you need to force a page break after that (i.e. this isn't the end of the document, the `\eject` command is defined as `\vfill\break`, so add `SILE.call("eject")` after the above to start the next page.
