### ISSUE TITLE
How to center vertically?

### ISSUE THREAD

**Issue by kstenerud** [simoncozens/sile#475]
Is there a way to center a block of text vertically on the page in sile?

**Comment by simoncozens** [comment]
Hi. I'm really sorry I'm behind on responding to issues. Thankfully you got me at a good time and this is an easy one.

Long answer: Yes, this is possible. Here's how I would think about this. You want to put some infinitely stretchy vertical glue at the start of your block of text, then your text, then another infinitely stretchy vertical glue at the bottom. Then the block of text will be balanced perfectly between two large spaces.

Now you need to know that SILE always puts infinitely stretchy glue at the bottom of a page anyway, so that material on pages which aren't full don't get stretched. So we don't need to add that ourselves. You also need to know that when SILE outputs a page, it normally discards any initial glue from the page so that every bit of material starts at the same place at the top. So we need to put some dummy material in there before the first piece of glue to stop SILE from stealing it. The usual bit of dummy material is an empty `\hbox`. So, empty `\hbox`, then a `\vfill`, then your text, then `\eject`.

Short answer:
```TeX
\hbox
\vfill
{ Stuff here will be centered on the page }
% We don't need a \vfill here because SILE provides one.
\eject
```

**Comment by kstenerud** [comment]
Perfect! Thanks!
