### ISSUE TITLE
unichar does not work as expected with "SILE.call"

### ISSUE THREAD

**Issue by nomanomanomanoma** [simoncozens/sile#513]
SILE.call("unichar", {}, "U+0049")

I would expect an ``I`` (capital 'i') to be printed but I get an ``U``.

**Comment by alerque** [comment]
That's because you are passing a string instead of an array. The variables to all `SILE.call()` functions are as follows:

1. the name of the function to call
2. a table of options
3. a table of content

You are passing a string instead of the table, so when the function looks for the first entry in the table it ends up with the first character of your string, a literal `U` character.

You need to call it like this:

    SILE.call("unicodechar", {}, { "U+0049" })

**Comment by nomanomanomanoma** [comment]
Thanks!
