### ISSUE TITLE
How to make the language file work

### ISSUE THREAD

**Issue by Yoxem** [simoncozens/sile#523]
I've fork ja.lua to make another language setting file zh.lua (incomplete,see [zh.lua.zip](https://github.com/simoncozens/sile/files/1800569/zh.lua.zip)), and I put it in sile/languages folder. but after I build sile with ``make clean;make;sudo make install``, I can't load the languages file while executing sile:
  This is SILE 0.9.5-unreleased
  <test.sil>
  No patterns for language zh
  [1] 

test.sil are like:
\begin[class=jplain]{document}
\script[src=packages/font-fallback]
\font[family=Noto Serif CJK TC,language=zh]
.....

**Comment by simoncozens** [comment]
Generally this means your file is not compiling. There's a line in`core/languages.lua` which is commented out:

      -- SU.warn("Error loading language " .. language .. ": " .. fail)

I don't remember why I commented it out. Uncomment it and you will get errors when your language file doesn't compile.

**Comment by Yoxem** [comment]
Ok, I've solved the problem. Thank you.

**Comment by alerque** [comment]
@simoncozens You didn't comment it out. I did. But I cannot remember why either and my commit message for doing so isn't helping (see 51720c3). I suspect it was a debug commit for local testing that I shouldn't have pushed before rebasing with more description and maybe removing instead of commenting the code. That's what I usually do, hack around locally commenting things, commit to try different things, then when it all works go back and rebase to cleanup the final code and give it more verbose commit messages. It looks like I might have been in a hurry trying to get a book out and that process got short circuited and now I don't know why that output was a problem.

I'm guessing it was showing up warnings by the thousands and spamming book build logs on my CI server.
