### ISSUE TITLE
harfbuzz 1.0.1: compiles but doesn't load

### ISSUE THREAD

**Issue by Eli-the-Bearded** [simoncozens/sile#539]
Ubuntu 16.04, git cloned the current master (ee610d89620aa6d30978aadac142c85b9ca8d4d3) installed everything `configure` wanted and then did the `make install`.
```
$ ./sile examples/test.sil 
This is SILE 0.9.5-unreleased
<examples/test.sil>

libtexpdf:fatal: texpdf_dev_locate_font() called with the zero ptsize.
$ ls -l examples/test.pdf
-rw-rw-r-- 1 elijah elijah 15 Sep  4 21:31 examples/test.pdf
$
```
When I run `make test` that also dies with a PDF related issue:

```
### Regression testing tests/pdf.sil
This is SILE 0.9.5-unreleased
<tests/pdf.sil>

! pdf package requires libtexpdf backend at tests/pdf.sil l.2, col.1
Makefile:936: recipe for target 'test' failed
make: *** [test] Error 1
```

But libtexpdf was installed (and I ran `ldconfig` as root afterwards).

Are the install directions incomplete?

**Comment by simoncozens** [comment]
OK, I haven't seen the first problem before, but it seems to happen when point size is zero (duh, obviously.) Could you run with `--debug=fonts`?

**Comment by Eli-the-Bearded** [comment]
```
./sile --debug=fonts examples/test.sil
This is SILE 0.9.5-unreleased
<examples/test.sil>
[fonts] Looking for DejaVu Sans;20;700;Bold Condensed;normal;;LTR
[fonts] Resolved font family DejaVu Sans -> /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
[fonts] Looking for Gentium Plus;10;400;;normal;;LTR
[fonts] Resolved font family Gentium Plus -> /usr/share/fonts/opentype/gentiumplus/GentiumPlus-R.ttf
[fonts] Looking for Gentium Plus;9;400;;normal;;LTR
[fonts] Resolved font family Gentium Plus -> /usr/share/fonts/opentype/gentiumplus/GentiumPlus-R.ttf
[fonts] Looking for Gentium Plus;10;400;Italic;normal;;LTR
[fonts] Resolved font family Gentium Plus -> /usr/share/fonts/opentype/gentiumplus/GentiumPlus-I.ttf
[fonts] Looking for Gentium Plus;0;400;;normal;;LTR
[fonts] Resolved font family Gentium Plus -> /usr/share/fonts/opentype/gentiumplus/GentiumPlus-R.ttf

libtexpdf:fatal: texpdf_dev_locate_font() called with the zero ptsize.
```

**Comment by simoncozens** [comment]
OK, I think both are shared library issues. SILE is trying to measure x height, but `SILE.shaper:measureChar("x")` is failing, which suggest it can't talk to harfbuzz - and the other issue suggests it can't talk to libtexpdf.

Open the SILE repl and try:
```lua
> require("justenoughharfbuzz")
```

and see what error you get.

**Comment by Eli-the-Bearded** [comment]
It doesn't look like an error.

```
./sile                                
This is SILE 0.9.5-unreleased
> require("justenoughharfbuzz")
{_shape=function: 0x7fa70f40ca80,get_table=function: 0x7fa70f40c980,shapers=function: 0x7fa70f40c930,version=function: 0x7fa70f40c890}
> 
```

**Comment by Eli-the-Bearded** [comment]
What system do you do development on? I know I tried sile once before, on a different computer, and I think I ran into issues there, too. The exact outcome is a too vague a memory now, just that I'm sure I didn't end up using sile for that project. And I know that was another Ubuntu system.

**Comment by alerque** [comment]
I don't know what Simon uses personally, but the Travis containers we're doing CI tests with are Ubuntu. The `.travis.yml` file has code that takes a clean Ubuntu base system and gets sile up and running to run tests. We know it _can_ be made to work on Ubuntu. I think it's kind of silly we don't have a *.deb package build system setup and a repository with the proper dependencies ready to go, but I'm not on Ubuntu myself so it's kind of hard to get going.

On Arch linux it should work out of the box as an AUR package either [stable](https://aur.archlinux.org/packages/sile) or [development](https://aur.archlinux.org/packages/sile-git) packages are available. With an AUR helper either of these can be installed with just one command and all dependencies are fulfilled with Arch packages.

**Comment by mnjames** [comment]
I'm using SILE on an Ubuntu system... sort of. I'm running it under the
Windows System for Linux, but my understanding is that the Ubuntu running
in that is the same as stock. And I've run it in a virtual machine Kubuntu
image in the past. That's just to say that it should definitely work.

I remember getting an error very similar to yours and also remember that
the solution was a missing dependency, but I don't remember what that
dependency was. I do remember that it was not obvious.

Also, in order to get graphite working correctly in SILE I had to go back
and build freetype2, fontconfig, graphite2, and harfbuzz from source. It's
possible that building one of those fixed the zero point size problem I was
having. Keep in mind that if you're changing dependencies, you'll need to
re-build SILE again after doing that.

--Malachi

**Comment by Eli-the-Bearded** [comment]
Those two comments were interesting and useful. I didn't look for a travis file. But now that I have looked at it, I see that it **does not** use the Ubuntu harfbuzz package. Instead it downloads, compiles, and installs a specific version. When I do that, the example/test.sile file works.

I think that this should be added to the build instructions.

**Comment by simoncozens** [comment]
Huh, Ubuntu 16 has harfbuzz 1.0.1, which *should* have the built-in OT support. (SILE requires a fairly recent harfbuzz; versions after 1.0.0 do the font loading internally, which avoids a dependency on Freetype and is much faster.) Don't know why 1.0.1 wasn't working for you. We should investigate further.

**Comment by Eli-the-Bearded** [comment]
Well, there's that, *and* (it hadn't finished running), `make test` still fails for me even after `make install`. Want me to open that as a separate issue?

```
### Regression testing tests/pdf.sil
This is SILE 0.9.5-unreleased
<tests/pdf.sil>

! pdf package requires libtexpdf backend at tests/pdf.sil l.2, col.1
Makefile:936: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by Eli-the-Bearded** [comment]
Oh, and Firefox on Ubuntu 16 apparently doesn't like harfbuzz 1.7.1.

(Doesn't like in the sense that it uses libraries that don't like my compiled version. `/usr/lib/firefox/firefox: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_glib_script_to_script`)

Fun times, fun times.

**Comment by simoncozens** [comment]
Looks to be 1.0.1: https://launchpad.net/ubuntu/xenial/+source/harfbuzz

**Comment by alerque** [comment]
What's the oldest Ubuntu we'll officially be able to support compiling and running SILE on?

* [Release Timeline](https://ubuntu.com/about/release-cycle)
* [Release Code Names](https://wiki.ubuntu.com/DevelopmentCodeNames)

It looks like the current LTS release is 18.04 (Bionic Beaver) and [has Harfbuzz 1.7.2](https://packages.ubuntu.com/search?keywords=harfbuzz&searchon=names&suite=bionic&section=all) and [Lua 5.3](https://packages.ubuntu.com/bionic/lua5.3).

Anything else we need?

Any burning need to accommodate older releases at this point?

**Comment by alerque** [comment]
@mnjames Any input here on my previous question^^^? What version of Ubuntu is currently to be expected under WSL?

**Comment by mnjames** [comment]
WSL allows you to install different Linux distros. At least Ubuntu 16.04 and 18.04 are available (I'm not sure about others). I'm now running 18.04 and I assume the default harfbuzz version on it works fine.

IMHO, SILE ought support at least the most recent LTS version of Ubuntu. Which at this point seems to have a recent enough version of harfbuzz. I don't know that SILE needs to go out of it's way to support 16.04, but maybe the documentation should mention in a footnote that it doesn't and link to a page on how to compile harfbuzz from scratch.

I realized looking through my comments above that I hadn't fully explained why I was doing some of what I wrote. I was compiling harfbuzz (and many other dependencies) by hand not because of SILE requirements, but because our font requires quite recent versions of many of them.

**Comment by alerque** [comment]
Thanks for the feedback @mnjames. I think that makes perfect sense. In that case the namesake of this issue is pretty irrelevant because harfbuzz 1.0.1 is not supported nor any distro that includes it, but I'll wait to close this issue until that is properly documented somewhere. Ubuntu 16.04 is the obvious distro in specific to call out for this, but we'll be mentioning minimum versions in general (currently our minimum supported Harfbuzz version is 1.4.2).
