### ISSUE TITLE
Bigger paragraph indent when using \par instead of new line

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#54]
\par command is an alternative of blank line (AFAIK). However, it leads to bigger indents than required.
This is OK, both indents are 1 cm:
```
\begin[papersize=a4, class=book]{document}
\set[parameter=document.parindent, value=10mm]
\set[parameter=current.parindent, value=10mm]
First line

First word, first paragraph.

First word, second paragraph.
\end{document}
```
But this produces an extra horizontal glue before the first line of the first paragraph:
```
\begin[papersize=a4, class=book]{document}
\set[parameter=document.parindent, value=10mm]
\set[parameter=current.parindent, value=10mm]
First line \par
First word, first paragraph.

First word, second paragraph.
\end{document}
```
Tested on the latest master.

**Comment by simoncozens** [comment]
This is sort of a bug and sort of not. It's not actually the `\par` that's adding the space. What is happening is that the `\par` is providing the new line, and then immediately following it there is a newline character. Newlines are always converted into spaces, meaning there is a space at the beginning of the line; it's this space which is providing the extra horizontal glue.

SILE's behaviour at present is consistent but perhaps not optimal. TeX ignores line-initial spaces so that

```
Foo

 Bar
```

produces output that is lined up. I'll have to think about whether SILE should do that as well. Consistent is good when the input is coming from a computer-generated source such as XML or a database, but human-friendly is nice when the source is human-generated. Maybe the answer is to do this for the TeX-like format only, but that's even more weirdly inconsistent.

**Comment by strepon** [comment]
OK, I see - I didn't realize that the simple newline can be so important:)) You are right that it behaves consistently, so for me it is enough to know that paragraphs should begin immediately after \par.

**Comment by pkulchenko** [comment]
@strepon, @simoncozens, as far as I understand, the workaround is to add comment `%` after \par; this will turn the newline into comment, thus eliminating the issue.

Simon, I think this should be the default behavior (ignore all newlines after commands), which will fix this issues as well as the issue I see with newlines after `\script` and similar tags.

Maybe you need to ignore not just newlines, but all whitespaces after commands (if there is nothing else on that line); if I need to add a new line, I can do it explicitly and if I need to add a whitespace (not sure why I would), there is still a way to do this for me by adding explicit comment `\par   %`.
