### ISSUE TITLE
Wider space between paragraph for accented letters

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#70]
This is rather a point for discussion than a bugreport. The following code:
```
\begin[papersize=a5]{document}
\font[size=10pt, family=Times New Roman, language=cs]

1. etapa: Studenec (kostelecko) – Studenec (hasičárna)

2. etapa: Studenec (hasičárna) – Studenec (řeznictví Nosek)

3. etapa: Studenec (řeznictví Nosek) – Studenec (Špice)

musí být hotová do konce letošního května.
\end{document}
```
produces this result:
![ukazka_sile](https://cloud.githubusercontent.com/assets/9050387/7221342/724cbdc4-e6e7-11e4-9d2b-79b7ea106d1b.png)

You can notice a slightly wider space between the second and the third paragraph caused by the accented letter "Š" (and such spaces are sometimes disturbing). I didn't succeed to change it by some of the *skip settings. Is this expected or is there any problem with accented fonts or languages?

For comparison, LaTeX makes the spaces equal:
![ukazka_tex](https://cloud.githubusercontent.com/assets/9050387/7221349/f5696e00-e6e7-11e4-9ae8-7393f6e9ba1f.png)

**Comment by alerque** [comment]
This issue is mentioned in the [FAQ on the Wiki][ugly], but I think it warrants further discussion as this (and a few other case's I've been seeing) leave me the impression that the issue is a touch more egregious in SILE than it usually is on LaTeX. 

  [ugly]: https://github.com/simoncozens/sile/wiki/faq#comments-about-ugly-output

**Comment by simoncozens** [comment]
The FAQ issue is slightly different, I think, or at least this is a special case of it. The FAQ is about the fact that both TeX and SILE increase the leading between lines where you have descenders on top and ascenders on the bottom, and therefore the leading between two lines is variable. I can't actually find a reference in standard typography which supports this idea, (so maybe we shouldn't do it) but the point of the FAQ is that SILE is doing something that TeX also does.

What's going on here is different - something that TeX doesn't do.

SILE determines the height of a line by the height of the characters in it (that makes sense), but it doesn't consider diacritics in that calculation. So when it sees a Š, it naturally sees a taller line than one with a S. And because it sees a taller line, it leaves additional space to compensate. But perhaps it should also be aware that the háček is separate to the "base" letter.

What confuses me about this is that we use exactly the same method as XeTeX for determining the height and depth of a character. So I wonder if XeTeX is doing something to ensure that the leading is sufficiently wide as to encompass even capitals with accents. Certainly it gets the global font ascent metric (which is unfortunately font-dependent but *can* mean the height of the tallest character with accents) as part of `ot_get_font_metrics`, but then what does it do with it?

@khaledhosny, can you help?

**Comment by khaledhosny** [comment]
No idea, really. but I think XeTeX computes the leading just the same way as legacy TeX (which I think is controlled by some primitives with defaults pre-loaded in the format).

**Comment by simoncozens** [comment]
Oh, I see why this is happening. And yeah, it's a major, fundamental bug. Leading is being applied (correctly, I think) between the lines of a paragraph, but not between paragraphs - you just get a constant parskip glue. I'll fix this ASAP.

**Comment by strepon** [comment]
Thanks a lot! Really nice to see how SILE becomes more and more perfect:))
