### ISSUE TITLE
It's better to not include *.pdf in the repo

### ISSUE THREAD

**Issue by Passw** [simoncozens/sile#85]
@simoncozens There are some *.pdf files, which are the output of  ```sile *.sil```.
I think it's better to remove this *.pdf files, to take down the size of repo :)

**Comment by simoncozens** [comment]
To be honest the PDFs are not all that big - the biggest is 1.6M. There was a King James' Bible in there which wasn't a good example of anything so I've removed it now, but I think it's important to have the PDF output in there so that (a) people can quickly explore SILE's capabilities before they try playing with it, and (b) they know what they should be getting when they do play with it. So I shall be keeping them!
