### ISSUE TITLE
The way relative paths are treated should be sanitized

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#91]
The way relative paths inside .sil documents are treated leaves something to be desired. On the one hand I don't want to see SILE getting into the mess that LaTeX has by doing searches through a huge path stack, but on the other it does need a touch more intelligence than it has now.

Currently by default SILE uses the CWD for searches. This, for example, means that in order to compile the documentation you must be in the repo root folder and run `sile documentation/sile.sil` but in order to compile most of the things in the tests directory you must be _in_ the tests directory, or to compile the sbgnt example you must be in examples/sbgnt. That the CWD is going to matter is neither apparent nor consistent with the way most non-shell applications handle paths. In the case of shell scripts that have dependencies on other scripts is common practice to retrieve the script's location using variations of `basename` and reference all relative paths on the computed value.

**I propose that relative paths in .sil documents be treated as relative to FILE rather than to CWD by default.** This way I could be in the root directory and run `sile examples/*.sil` or be in the examples directory and run `sile *.sil` and achieve exactly the same thing even in the case of documents that import other documents.

I further suggest that the sile executable accept an include path search argument (in fact accepting it multiple times) that adds paths to a stack to look in if files are not found relative to the document being compiled. This would enable additionally flexibility at document compile time.

**Comment by simoncozens** [comment]
The last part is available through the `SILE_PATH` environment variable. 

The first part... I'd love to see a patch. ;-) And it should be pretty easy to implement: `SILE.require` in `sile.lua` is currently a thin wrapper around Lua's `require`, so that's the place to customize file look-up when loading Lua-based packages and classes. For including other SILE documents, `SILE.resolveFile` (also in `sile.lua`) does half of what you want. The current file is stored in `SILE.currentlyProcessingFile`.

**Comment by alerque** [comment]
I'm still feeling my way around the code, but I'll have a look at it. Thanks for the pointers to get me started.
