### ISSUE TITLE
\script command interprets braces as grouping operators

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/sile#92]
`\script{ a = { "a"; "b"; "c" } }` will fail because the parser will eat the braces and not pass them to Lua.

**Comment by pkulchenko** [comment]
Simon, wouldn't you need to have a Lua parser embedded as this needs to handle things like `\script{ a = { "a"; "}"; [[}]] } }` and similar ones?

**Comment by simoncozens** [comment]
I think I'm not going to fix this. If you are doing anything serious with SILE, you should be using (a) separate Lua files and/or (b) XML mode. Either of those will solve the problem. TeXlike-mode is just for toy examples and tests.

**Comment by pkulchenko** [comment]
@simoncozens, this makes sense, but maybe require/allow using `[=*[` or `{=*{` as separators for the scripts, which may help to avoid this issue?
Something like this: `\script{{ a = { "a"; "b"; "c" } }}` or `\script{[[a = { "a"; "b"; "c" }]]}`?

Having one file has advantage for generated files, which includes everything needed without storing/referencing intermediate files. I haven't gotten to this point yet, but it would help in my case as well when I need to inject Lua code into SILE files and still keep it as one file.

**Comment by alerque** [comment]
This is a problem that EOF markers solve in other languages. Whatever the opening marker is, the parser skips to the second instance of the marker. Not having access to basic syntax like `{}` inline is pretty frustrating actually, and _any_ syntax that allows this seems like a good idea. It exists the other way in Lua—you can inline any TeX like SILE syntax using Lua's heredoc:

    SILE.doTexlike([[
    \define[command=book:monofont]{\font[family=Hack]{\process}}
    ]])

The reverse would seem like a reasonable approach. Otherwise even having the `\script{content}` syntax is kind of misleading since nearly anything you put in it will be broken. Heredoc syntax could also be eminently useful for verbatim environments.

**Comment by alerque** [comment]
I'm re-opening this issue because my PR for #450 also fixes this issue.
